### ISSUE TITLE
oggec and sox versions

### ISSUE THREAD

**Issue by GwendolyneFreddy** [Gibberlings3/RealMod#9]
Are these versions the last updated ones?

**Comment by mike1072** [comment]
- OggDec is v1.9.7
    - There's a v1.10.1 on [this page](https://www.rarewares.org/ogg-oggdec.php)
- sox is 14.4.1
    - There's a 14.4.2 on [this page](https://sourceforge.net/projects/sox/files/sox/14.4.2/)

**Comment by GwendolyneFreddy** [comment]
Thanks. I guess I will use the RealMod versions to update old mods.

**Comment by mike1072** [comment]
Prior to 2014, [mods were often packaged with an old version of sox](http://forums.pocketplane.net/index.php/topic,29070.msg335065.html#msg335065) that was compiled for the PowerPC architecture, which is good for Apple computers made before 2006, but not for modern ones.

So, it's quite important to update any mods that have a version of sox with a 2002 timestamp.
